yegor256/tacit

index.html

`label` was not responding to clicks/taps

Fixed: Sample page consnet label target

---

scss/_tables.scss

Since the Android's fallback font Arial does not have a sensible font-weight: 500 and the Helvetica Neue looked too bold with 600, there's now added emphasis when using <thead>.
This is because the <th> can also be somewhere else, e.g. the first element of the row:
```html
<table>
<tbody>
<tr>
<th>Name</th>
<td>Cat</td>
<td>Human</td>
</tr>
<tr>
<th>Legs</th>
<td>4</td>
<td>2</td>
</tr>
</tbody>
</table>
```
In that case it makes no sense to always have the <th> tag have different margins and borders, just when it is inside the <thead> tag.
Quick screenshot:

Andriod th boldness fix

---

scss/_responsive.scss

Seems that there are browser hacks that W3C validator treats as warnings instead of errors.
Screenshot of the compiled css at W3C validator (with default configuration):
Result: The firefox hack now shows up as a warning.
Fixes #32

Fixed: W3C validator error

---

README.md
index.html

According to the HTML5 specification, section 4.8.4.11:
"The default type for resources given by the `stylesheet` keyword is `text/css`."

Removed explicit specification of the stylesheet type.

---

README.md

Hi
To get Grunt running I had to install scss-lint and compass, I've added it to the README in case you think it's a worthwhile addition.
Many thanks
Ben.

Update readme with gem installs for scss_lint and compass.

---

index.html

Added http prefix to a link. Previously resolved to file:// and failed.

Added http protocol to a link

---

scss/_media.scss

Our team uses tacit in [this site](http://nodejs.jp/) with the addition of `img { max-width: 100%; }`.
It has a good effect to big images in small screens.

Add img style

---

.rultor.yml
.travis.yml
README.md
appveyor.yml
package.json

Grunt v1 include grunt-cli in it and there's no need to require global cli install.

update grunt and use local grunt cli

---

scss/_tables.scss

I believe it's necessary for big tables.

#overflow: overflow for TD and TH

---

.rultor.yml
.sasslintrc
.scss-lint.yml
.travis.yml
CONTRIBUTING.md
Gruntfile.js
appveyor.yml
package.json

This PR tries to replace ruby dependencies from scss building and linting. (closes #72)
Here is summary of the changes:
- Replaced grunt-contrib-sass (depends on sass gem) with grunt-sass (depends on node-sass)
- Replaced grunt-scss-lint (depends on scss-lint gem) with grunt-sass-lint (depends sass-lint npm module)
- I created .scsslintrc which passes the current scss code without any error with minimal rule settings.
- Updated node.js version on travis to 4 because some of grunt-sass-lint deps only supports node.js >= 4 and unable to lint with node.js 0.12.
- I deleted lines about gem installation from CI setting files and contributing guides.

Remove ruby deps in sass building and linting

---

Gruntfile.js
index.html

This PR modifies `grunt shell` task to check if all the files which include the copyright line have the correct year in it. I included `*.js`, `*.scss`, `*.html` and LICENSE as target files.
closes #76

Modify grunt shell task to check copyright years

---

index.html
scss/_forms.scss

It looks like that the label can be used as a surrounding element without the `for` attribute, and it is [100% valid html5](https://www.w3.org/TR/html401/interact/forms.html#edef-LABEL).
This ultimately fixes the inlining issue with chrome #77 .

Fixed checkbox and radio input

---

scss/_forms.scss

- Removed crazy specificity for (almost) all input types 
- Removed double margin-bottom:
As stated in #106 labels can be used as a surrounding element:
```
<label>
Another field, this time inside label:
<input name="email" type="text" id="email" size="25" placeholder="must be unique"/>
</label>
```
This created a double margin bottom if used in 'normal' inputs:
- Also fixed inconsistent select margin

 Fixed spacing between form elements

---

scss/_grid.scss

Would be great to merge this too. We don't need that margin if the `P` is inside the `BLOCKQUOTE`.

#blockquote: no margin for P inside BLOCKQUOTE

---

Gruntfile.js
package.json

xargs usage does not seem cross-platform. ([See the comment](https://github.com/yegor256/tacit/issues/103#issuecomment-354238009)) So I rewrote `checkYear` task in javascript.
This also outputs better error messages when the required patterns are not found like:
```
Running "checkYear" task
>> The file, Gruntfile.js, does not include the pattern: 2015-2017
```
By this, we know which files have outdated copyright lines.

refactor: better checkYear task

---

README.md

`whoismining.com` doesn't seem using tacit anymore.

Remove whoismining.com from example websites

---

scss/_grid.scss

The responsive layout is broken, if we don't have these.

#inline-block: nav alignment

---

README.md

Added https://filfreire.com and https://moneeee.tech urls to the "Built with Tacit" section.

Add filfreire.com and moneeee.tech to README.md

---

scss/_grid.scss

Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:
- You made a small amount of changes (less than 100 lines, less than 10 files)
- You made changes related to only one bug (create separate PRs for separate problems)
- You are ready to defend your changes (there will be a code review)
- You don't touch what you don't understand
- You ran the build locally and it passed
This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html
Thank you for your contribution!
----
Hello,
Having an outline of 0 makes the links and buttons unusable by keyboard and creates huge problems with accessibility …

Remove default outline: 0

---

scss/_defs.scss

Yay! Use pretty system fonts in modern browsers :grin:

Pretty fonts :)

---

scss/_tables.scss

+ reduce table overal font size
+ make tables responsive (after 1024px they turn into plain lists)
related issues: #182 and #89
Current final result (checked in Chrome, Firefox and Safari):
**Desktop view:**
**"Mobile" view:**
@yegor256 fyi

 #188 - make tables responsive

---

scss/_tables.scss

Let's reverse the changes made. Tables should be the same size as normal text.

normal size for tables

---

scss/_defs.scss
scss/_forms.scss
scss/_grid.scss
scss/_pre.scss
scss/_responsive.scss

Fixes #216. All of the changes should be completely invisible with default browser settings, and only affect users who have a non-default font zoom level. To test the changes, go in the Chrome settings (or any browser) and increase the default font size.
Specific changes I did:
- Swaps the base `em` unit to use rems, and keeps using that throughout most of the styles.
- Moves the global font-size declarations so they are on `body` only, to avoid redefining the root font-size on `html`.
And then I did more opinionated changes, which I don’t think are strictly needed, but hopefully make this a bit nicer:
- Using a `px` size for border-radius so they are consistent regardless of zoom level
- Using the same px size for any padding that changes the layout significantly
- And in a few cases …

Switch base size unit to be defined in rem for text resizing. Fix #216

---

Gruntfile.js
LICENSE
index.html
package.json
scss/_defs.scss
scss/_forms.scss
scss/_grid.scss
scss/_headings.scss
scss/_pre.scss
scss/_responsive.scss
scss/_tables.scss
scss/_typography.scss
scss/main.scss

This allows to just do
```typescript
import 'tacit-css'
```
instead of
```typescript
import 'tacit-css/dist/tacit-css-1.6.0.css'
```
in your JS code when using a bundler like Webpack.

Point main to CSS file for usage by bundlers

---

scss/_common.scss
scss/main.scss

This PR adds a **_defs.scss** include file to handle general style rules that are not strictly related to the grid.
For now, this file handles hiding of any element with the `hidden` attribute via `display: none`.

implement respecting hidden attribute

---

scss/_defs.scss
scss/_forms.scss
scss/_functions.scss
scss/_grid.scss
scss/_pre.scss
scss/_tables.scss
scss/main.scss

In this PR, I’ve applied minimal fixes to remove deprecation warnings from the Sass build, specifically:
- Replaced the deprecated darken() and lighten() functions with the new safe-adjust-lightness() wrapper
- Fixed deprecated number / number division by replacing it with calc()
fixes #314 
There are still some deprecation warning around using @import. I started exploring replacing all @import with @use, but doing that properly would require:
- Updating all SCSS files to match new Sass module rules
- Refactoring how variables and mixins are shared between files
- Dropping Grunt’s sasslint since it’s incompatible with the new Sass syntax
- Potentially replacing the Grunt-based build system with a more modern setup (like npm scripts) for easier long-term maintenance.
Let me know if you …

chore(sass): minimal deprecation fixes (darken, lighten, math.div)
