scss/_responsive.scss
Fixes the form overflow problem:
=> Fix form field overflow

scss/_responsive.scss, scss/_tables.scss
Tested to work on ios, android (chrome + native), latest chrome + FF + safari, IE10+.
IE9 buggy, the table does not understand css well.
=> Added: Table responsiveness

index.html, scss/_headers.scss, scss/_typography.scss
H4, H5 and H6 should attract less attention than H1, H2 and H3 ;)
=> Added logical heading styles for H4, H5 and H6

index.html, scss/_forms.scss
I added a "disabled" style for the default button (issue-#21), and I tweaked the colors of the default button's style since its too dark, that it looks like a "disabled" button rather than a clickable one (issue-#22).
Please check my work if its applicable or if there's any problem with it. Thanks.
=> Added "disabled" style for button (default) and tweaked button's color for readability

.rultor.yml, Gruntfile.js
@yegor256 can you check the rultor script modifications? This change should push the newest compiled css files in the `dist/` folder automatically to the master branch. 
Fixes #27
=> Add dist/ folder with .css, .min.css and .min.css.map files to GitHub

index.html
This typo jumped out at me, here's a quick fix.
=> Minor grammar improvement

index.html
This pull request just fixes a few typos in the example page.
=> Fixed typos in example

index.html, scss/_defs.scss, scss/_forms.scss, scss/_grid.scss, scss/_headings.scss, scss/_pre.scss, scss/_responsive.scss, scss/_typography.scss
This includes a number of fixes and expansions. Updates for flexbox forms. Additions for definition list, blockquote, image, figure, and more. Margin fixes and padding matches across a number of elements. Test HTML expanded.
Thanks for creating this clean little framework! It's been great for wiring up proof of concept projects.
=> Expand coverage

index.html
Shifted to https wherever possible
=> Updates links to use https

README.md
=> Shifts to HTTPS links in readme

.gitignore, index.html
Fix for https://github.com/yegor256/tacit/issues/74
=>  #74 update index footer date

README.md
Issue https://github.com/yegor256/tacit/issues/86
=>  #86 add license to README

index.html
issue or recommendation #91 
since I check it myself it's clean and perfect so I add that batch in the index.html
=> add a w3c css batch next to github stars batch

CONTRIBUTING.md, README.md
@yegor256 please follow-up
Related Github issue https://github.com/yegor256/tacit/issues/73
=>  #73 add contributing.md

README.md, index.html
@yegor256 please follow-up. This is related to issue #31
=>  #31 browser compatibility table

index.html
- Fixed labels for wrong inputs
- Added values for age radios 
- Added `lang="en"` to html tag
=> Fixed HTML5 syntax

index.html, scss/_forms.scss
=> change the link #97

scss/_tables.scss
=> vertical-align for TD/TH

index.html, scss/_defs.scss, scss/_forms.scss, scss/_pre.scss
per issue #114 I'm submitting a pull request to fix issues reported by lighthouse including color contrast.
I tried to stick as closely to the original colors as possible, altering their brightness, but retaining their hue. Hopefully a graphic designer can improve upon the values that I came up with.
https://webaim.org/resources/contrastchecker/ was used to select values that would pass all of the tests.
=> fixed contrast issues

README.md
=> Add built with Tacit section

README.md
=> more projects to the list

index.html
=>  #125 - add tacit logo to top of index page

index.html
=> #124 - add Tacit logo to shortcut icon

CONTRIBUTING.md
Related to issue #109.
@yegor256 FYI
=> #109 - add git commit guidelines

scss/_headings.scss
Would be great to merge this and release a new version. Thanks.
=> #layout: line-height for headings

README.md
=>  #113 - add socatar.com to "built with tacit"

Gruntfile.js, LICENSE, README.md, index.html, scss/_defs.scss, scss/_forms.scss, scss/_grid.scss, scss/_headings.scss, scss/_pre.scss, scss/_responsive.scss, scss/_tables.scss, scss/_typography.scss, scss/main.scss
=> Bump year version to 2018

README.md
=> #143 A small mistake with href in README

README.md
PR to tackle issue #145 
/cc @alex-semenyuk 
@yegor256 please review.
=> #145 - Add contributing info to readme

index.html
=>  #148 - fix stretched tacit logo

scss/_tables.scss
I believe, this is how it should be.
=> display table

package.json, scss/_grid.scss
Let's roll back some recent changes, they were wrong
=> layout rollback

README.md
=> Add other tacit related frameworks #163

README.md
Add https://kimeiga.github.io/bahunya/ framework mention on README
/cc @yegor256 @Kimeiga
=> Add Bahunya mention

README.md
versioneye service is no longer exist.
=> README.md: remove broken link to versioneye

index.html
=>  #170 - fix download link in index page

index.html
Related document about svg support on android 2.3.3: https://stackoverflow.com/questions/3889882/svg-support-on-android
=>  #147 - tacit logo doesn't load on android 2.3.3

.rultor.yml, Gruntfile.js, LICENSE, README.md, index.html, scss/_defs.scss, scss/_forms.scss, scss/_grid.scss, scss/_headings.scss, scss/_pre.scss, scss/_responsive.scss, scss/_tables.scss, scss/_typography.scss, scss/main.scss
`npm test` command currently fails with date validation. Updating date across all needed files.
=> Bump date 2019

.rultor.yml
=>  #177 fix --no-ri issue

scss/_grid.scss, scss/_headings.scss
Let's get rid of the radius for the `<article>`
=> no radius for the border

README.md
Using slightly modified version of tacit for golang.cafe
=> Adds golang.cafe as tacit css example

scss/_forms.scss
Should fix the rendering, see #211
=> #211 block inside fieldset

README.md
**[tinyfts](https://github.com/dbohdan/tinyfts)** is a very small open source full text search server that uses Tacit for its Web UI.  ~[Demo](https://tws.dbohdan.com/).~
=> Add use case: tinyfts

Gruntfile.js, LICENSE, index.html, scss/_defs.scss, scss/_forms.scss, scss/_grid.scss, scss/_headings.scss, scss/_pre.scss, scss/_responsive.scss, scss/_tables.scss, scss/_typography.scss, scss/main.scss
fixes failing checkyear npm test task.
=> fix checkyear for 2021

Gruntfile.js, package.json
@tmpfs this PR should help avert the issue https://github.com/yegor256/tacit/issues/210 on duplicate css declarations in the final css file.
=> #210 fix duplicate css declarations.

index.html
Fix `GET https://placehold.it/900x500 net::ERR_CERT_DATE_INVALID`
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:
- You made a small amount of changes (less than 100 lines, less than 10 files)
- You made changes related to only one bug (create separate PRs for separate problems)
- You are ready to defend your changes (there will be a code review)
- You don't touch what you don't understand
- You ran the build locally and it passed
This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html
Thank you for your contribution!
=> fix: replace img url in images example

index.html
added details and summary so you can integrate css pull request for them
=> details&summary example
